name: test

on:
  push:
    branches: 
    - main
    paths:
    - src/**
  pull_request:
    branches: 
    - main
    paths:
    - src/**

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Update npm
        run: npm install -g npm

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        
      - name: Run Lint
        run: npm run lint
      
      - name: Run Unit Tests
        run: npm run test:unit

      - name: Run E2E Tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
